"""made changess

Revision ID: 599613b08090
Revises: d561173d0aa6
Create Date: 2024-12-14 22:15:18.184224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599613b08090'
down_revision = 'd561173d0aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wallet_balance')

    # ### end Alembic commands ###
