"""changed CartItem

Revision ID: d561173d0aa6
Revises: 
Create Date: 2024-11-30 00:07:00.657844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd561173d0aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_cart_product', ['cart_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('unique_cart_product', type_='unique')

    # ### end Alembic commands ###
